### ISSUE TITLE
recive mail

### ISSUE THREAD

**Issue by amirarabi** [adaline/dockermail#1]
Hi
I can send email but can not recive email!

I install rainloop in container and test connections (IMAP SMTP) is ok.

Do you have an idea!

Thanks

**Comment by adaline** [comment]
Hello :)
Are you having issues receiving mail in Rainloop or with an external client?
Assuming IMAP connection is fine, perhaps there is a TLS certificate issue, since the certificate is self-signed some clients may not like it.
If you let me know what you have tried so far and the results you got, i will try to help you find the issue.

**Comment by amirarabi** [comment]
I have issues reciving mail in Railoop.
please check my git:

https://github.com/amirarabi/mymail

**Comment by adaline** [comment]
Im not sure what the issue is from the git repo you linked.
I recommend you to make sure the email server provided by my docker setup works, set it up and test it with an email client such as Thunderbird.
Once you know that works, you can focus on trying to configure Rainloop container.

**Comment by SudoHenk** [comment]
I'm facing (I guess the same issue):

When I want to send to my dockermail I get the following: 
``` 
The mail system

<myemail@email>: unknown user: "myemail"
```

**Comment by adaline** [comment]
Hi @SudoHenk , I thin the issue is that your account was not set up correctly, Postfix cant find an inbox for the incoming message, hence the error `unknown user`.
If you can share your config so the issue can be replicated, I will try to find out what went wrong.

**Comment by SudoHenk** [comment]
I can send mails, but i can't recieve. What config would you like to see? I also noticed that my DKIM key is not send with the mails that i can send, my key is copied to `/etc/dkim.key` and i've used the default config for that. Any leads?

aliases (real information disclosed):
mail@email mail@email
@email mail@email
@email2 mail@email

domains:
email
email2

passwords:
mail@email: .. sha etc.. (can sent so i guess there is nothing wrong with this)

**Comment by adaline** [comment]
The files you describe seem fine, obviously I cant build the same container as you with these so I cant test the issue and find the problem.

I can only assume something is not configured correctly. You can run a shell inside the container `docker exec -it [container_name] bash` and try going through the settings script `process_settings` to see if each command works.

There is no need to rebuild the image, `process_settings` script is run every time the container starts and updates all the settings. Just restart the container when you update the settings.

**Comment by SudoHenk** [comment]
This is output that I get:
```
./process_settings
mkdir: cannot create directory '/etc/postfix/tmp': File exists
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "mail                                                             @mydomain"

```

It seems like it's running fine.

**Comment by adaline** [comment]
Does the "postmap: warning: /etc/postfix/virtual...." line really repeat like that? I don't think it should!

**Comment by adaline** [comment]
Here is my run of the same: 
```
root@e4322999f861:/# ./process_settings 
mkdir: cannot create directory '/etc/postfix/tmp': File exists
postmap: warning: /etc/postfix/virtual-mailbox-maps.db: duplicate entry: "hello@madespecial.co.uk"
root@e4322999f861:/# 
```

**Comment by SudoHenk** [comment]
I think its based on my aliases files. There is exactly that amount of lines.

I'm sending all mail from my root domains to 1 e-mail adres.
