### ISSUE TITLE
IMAPS + Letscrypt

### ISSUE THREAD

**Issue by prologic** [adaline/dockermail#12]
Let's add IMAPS and use [LetsEncrypt](https://letsencrypt.org/).

Let's borrow ideas for this from https://github.com/tomav/docker-mailserver

**Comment by adaline** [comment]
Hey James,
IMAPS should be an easy addition.
I would be inclined to make LetsEncrypt a module and therefore optional,
there is already a self-signed and own certificate option available in the core already -
LetsEncrypt would be another nice addition.

Will try to get some work on these features done soon, thank you for suggestions!

**Comment by prologic** [comment]
I agree; I really like the way you've architected your setup. I successfully got it up and running last night on a private domain. I think a letsencrypt should be a sepate container/image as well. While we're at it why don't we borrow from other docker images of mine and make the self-signed certs part another separate image too? e.g: Have a look at https://github.com/prologic/autodock-paas/blob/master/docker-compose.yml ; note the ``volumes_from: sslcerts`` and the ``mksslcerts`` image?

**Comment by prologic** [comment]
I've implemented IMAPS

**Comment by adaline** [comment]
Hi James,
I have added the imaps support from your branch.
It does not include the extra certificates you have in your fork, using standard certificates only.
Thank you for your work!

**Comment by adaline** [comment]
Letsencrypt is an awesome service, there are many images to use it already and it can be integrated with these email images without any changes. I would not want to write and maintain another copy :)

**Comment by prologic** [comment]
Cool thanks :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
