### ISSUE TITLE
Optimized Images (for size)

### ISSUE THREAD

**Issue by prologic** [adaline/dockermail#17]
Would you be opposed to switching out the base image being used for something a little more lean and mean? This is what we have at the moment:
```#!bas
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
dockermail_setup            latest              a92cbf4e5993        12 hours ago        27.96 MB
dockermail_opendkim         latest              50d95b1a7087        13 hours ago        153.5 MB
dockermail_core             latest              3dc9802c6691        13 hours ago        189.8 MB
dockermail_amavis           latest              ab7d07b116c0        13 hours ago        323.9 MB
```

Note that ``dockermail_setup`` is based on my [prologic/python-runtime](https://hub.docker.com/r/prologic/python-runtime/) which itself is based on [alpine](https://hub.docker.com/_/alpine/) (*a mere ~5BM with complete packaging*).

I *think* we could cut all of the image sizes in half pretty much based on my experience with Alpine; and pretty much all my Docker images these days are based off of Alpine :)

This would:

- Reduce download sizes
- Improve download/setup time
- Improve startup time

**Comment by adaline** [comment]
Hey James,
thank you so much for all the work and enthusiasm!
Sorry I am quite busy at the moment with work so had not had a chance to reply to all of your excellent suggestions.
I think having lean images would be awesome, im weary of making a project that is hard to play with for newcomers though.
Personally i would like to enable as many people as possible to hack and change these images however they like, or contribute to this project itself and i think having the most widely used Linux distro as the base really helps that.
I think in the spirit of open source i would like to concentrate on making this project easy to use and change for everyone, even if that is at the cost of some efficiency.

**Comment by prologic** [comment]
No worries. I haven't tried to do this yet; so maybe let's see what it's like. At worst though (*from an "easy" use point of view*) we're simply talking about swapping out ``apt-get install blah`` for ``apk -U add blah`` -- Mostly Alpine has many similarly named packages so that's a +1 :)

**Comment by adaline** [comment]
Hey James,
as per the response in the other issue, even though Alpine would slim these images down,
I am reluctant to move away from Ubuntu base image as it provides the most broad platform
for others to extend and modify these images.
Thanks for the suggestion :)

**Comment by prologic** [comment]
I understand :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
