### ISSUE TITLE
Force TLS on SMTP submission

### ISSUE THREAD

**Issue by prologic** [adaline/dockermail#18]
Done in my fork. We should merge this in too though; as well as the IMAPS support :)

**Comment by adaline** [comment]
Hi James,
I have added the outgoing TLS support, forcing it is non-standard behaviour and breaks compatibility.
So instead I have used the opportunistic level only, it will try to use TLS and if it fails it will use non TLS connection.

**Comment by prologic** [comment]
Cool thanks for letting me know :) Looks like I need to sync my fork with
yours :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
