### ISSUE TITLE
Add SPF Support

### ISSUE THREAD

**Issue by prologic** [adaline/dockermail#19]
It would be nice to add SPF support.

See: https://help.ubuntu.com/community/Postfix/SPF

**Comment by hheimbuerger** [comment]
@prologic I'd like to see that too. Have you already taken a shot at integrating it?

**Comment by prologic** [comment]
No I haven't tried to add this support yet.

**Comment by adaline** [comment]
SPF filter is already provided by the amavis module,
ideally I would like to include it in the core too, for people that dont use amavis module.
But it changes core image size from 180 to 260 MB, so im not sure its worth it.

**Comment by prologic** [comment]
Hmm :) This is why I think we should consider using alpine as a base image
:)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Tue, Apr 26, 2016 at 9:58 AM, Valentin Arkhipov <notifications@github.com

**Comment by adaline** [comment]
Using alpine base would no doubt slim down the images, but it would move the project away
from a well known base OS that lots of people already play with and being easy to hack is a
high priority for this project.
My goal for this project is not to be the final solution to all problems people may have,
but an easy building block to build all those solutions on top of :)

I think I will leave out replicating the SPF filter amavis already provides, idealogically if we
add support for SPF filtering to core we may as well add DKIM filter etc, which defeats the purpose
of having amavis module in the first place.
