### ISSUE TITLE
Full-featured alternative: dockerized iRedMail 

### ISSUE THREAD

**Issue by niieani** [adaline/dockermail#20]
Sorry to intrude on this massively awesome project @adaline - I've started working on something very related and I thought it might make sense to post it here so people can discover (if you feel otherwise, feel free to close this topic). 
It's a proper dockerization of iRedMail. There's still a little bit to do to make it work, but it looks promising. I'm looking for some help in finishing the v1, so if anybody needs something more than what `dockermail` offers, it would be great if we could join forces to make it functional.

As to the how: I'm hooking the official installer so it can run in the build process, switching on or off specific parts of the build. On top of that I'm caching the mysql queries executed during the installation so they can be applied once an instance is up.
It was quite a bit of work to get here, but now what's left is putting it all together - those small things like making sure the services talk to each other and not localhost, plus making a wrapper scripts that will boot up the necessary process.

Repo: https://github.com/niieani/iredmail-docker

**Comment by adaline** [comment]
I hope its going well with your project @niieani.
I'm having a clean up of the issues on this repo and will be closing this one,
as it has stayed up a good while now, hope it helped!

**Comment by niieani** [comment]
@adaline No problem. Actually I've been working hard on it but there were too many problems with it so I've moved to https://mailinabox.email/, which seems equally good, if not better in some cases, than iRedMail.

**Comment by adaline** [comment]
Looks nice and easy, good luck :+1:
