### ISSUE TITLE
Error "User exists more than once" when having multiple redirections to the same target

### ISSUE THREAD

**Issue by hheimbuerger** [adaline/dockermail#21]
I'm using postfix mostly to set up redirects to other (off-site) mailboxes. So a common configuration would look like this:

    "domains": {
        "alpha.com": [
            {"email": "example@gmail.com", "aliases": ["me@alpha.com"]}
        ],
        "beta.com": [
            {"email": "example@gmail.com', "aliases": ["me@beta.com"]}
        ]
    }

This results in the error message:

    auth: Error: passwd-file /etc/dovecot/passwd: User example@gmail.com exists more than once

Is this an unsupported configuration?

One workaround is to just group them together under the same domain. It seems like I don't have to put the redirection addresses under the domain they actually define a receiving (redirecting) address under. In fact, apparently they don't have to be under a valid domain at all.

So this works for example:

    "domains": {
        "alpha.com": [],
        "beta.com": [],
        "redirections": [
            {"email": "example@gmail.com", "aliases": ["me@alpha.com", "me@beta.com"]}
        ],
    }

Is there any downside or security risk to doing that?

**Comment by adaline** [comment]
Hey Henrik,
Clearly postfix does not like having a repeating email address, not an issue with Dockermail I would say - this project blindly passes any config you give it into relevant postfix config files. What postfix does with it is out of Dockermail remit.

I think your second config looks fine, all your are saying there is that you want to accept mail for alpha.com, beta.com and also for domain "redirections". If it works for you, means Postifx is happy with that.

**Comment by hheimbuerger** [comment]
But the JSON format is Dockermail's domain. Don't you think it's an indication of a structural issue, if it doesn't matter which domains you place the redirections under?

At the very least, I feel like this warrant some documentation. (Regarding the JSON format, so on the Dockermail side, not in Postfix.)

**Comment by hheimbuerger** [comment]
This also seems to result in one more restriction. Think of a configuration like this:

    "domains": {
        "alpha.com": [
            {"email": "mailbox@alpha.com", "password": "{PLAIN}pw"}
        ],
        "beta.com": [],
        "redirections": [
            {"email": "example@gmail.com", "aliases": ["me@alpha.com", "me@beta.com"]}
        ],
    }

This will result in the following warning:

    postfix/trivial-rewrite[184]: warning: do not list domain alpha.com in BOTH mydestination and virtual_mailbox_domains

and also, `mailbox@alpha.com` will *not* work in this case!

Could the JSON-to-Postfix-configuration converter resolve this problem and create a working configuration?

**Comment by adaline** [comment]
Hey Henrik,
All the aliases go to the same file in postfix, my decision to structure aliases within domains was made for clarity and brevity of the config file for its intended use case (hosting own mailboxes and redirecting mail to them).
This project was intended to make email hosting as easy as possible, I would not want to compromise that by having a verbose config file with every postfix quirk and option exposed.
I hope you understand what I'm trying to achieve :)

If you need to have very specific functionality, you can modify this project for your specific needs since all the code is provided.

**Comment by hheimbuerger** [comment]
@adaline I still think this is a an issue of this project, and not of postfix, so I've opened a PR that fixes it. Would you please consider reopening this issue?

**Comment by hheimbuerger** [comment]
For anyone stumbling upon this issue later: this bug has been fixed in @prologic's fork: https://github.com/prologic/dockermail/.

**Comment by adaline** [comment]
Hey Henrik, your fix looks nice and clean, I will merge it into this repo.
Thank you for the contribution!
