### ISSUE TITLE
Amavis denied access

### ISSUE THREAD

**Issue by darkblinded** [adaline/dockermail#26]
I started a dockermail service including opendkim and amavis as described [here](http://madespecial.co.uk/blog/2016/1/28/easy-private-email-hosting-with-dockermail) but was not able to send or receive any mail.  `docker attach <amavis container>` shows

```
...
2016-06-15T23:38:45.650245+00:00 bdf0c26a4548 amavis[52]: () (!)DENIED ACCESS from IP 10.42.153.172, policy bank ''
...
```
Do I have to configure amavis first? If so documentation or a link to documentation would be nice.

**Comment by adaline** [comment]
Hey Leonard,
Amavis uses the same config.js as the core, as long as the same settings folder is mounted to both containers - it should work.
If you are still having issues, send me your config.js and your docker-compose/startup commands and i will try to find out whats causing an issue. You can find my email in the github profile.

**Comment by adaline** [comment]
Have not heard back with more details on the issue, assuming problem solved
