### ISSUE TITLE
/etc/postfix/virtual-mailbox-maps generation

### ISSUE THREAD

**Issue by y-ponomarev** [adaline/dockermail#4]
It can be more accurate to generate the file `/etc/postfix/virtual-mailbox-maps` from the `/etc/dovecot/passwd` instead of `/etc/postfix/virtual`.

In `boot` script:
```
...
# Add password file
cp /mail_settings/passwords /etc/dovecot/passwd
# Parse mailbox settings
mkdir /etc/postfix/tmp
awk < /etc/dovecot/passwd 'BEGIN {FS= ":"}; {print $1}' > /etc/postfix/tmp/virtual-receivers
...
```

**Comment by adaline** [comment]
I will go through and fix it up, or you can push a PR if you like to contribute the solution :)
My plan is to use JSON config instead of current flat files with the next release, I think it would make it cleaner and easier to admin with external tools.
