### ISSUE TITLE
Sample settings? /opt/dockermail/settings

### ISSUE THREAD

**Issue by prologic** [adaline/dockermail#5]
Need to put thse in the repo somewhere
and remove the *assumption* of ``/opt/dockermail/settings`` in the [docker-compose.yml](https://github.com/adaline/dockermail/blob/master/docker-compose.yml) -- Right now (*I'm following your repo*) I don't fully understand how to spin this up as-is (yet) :)

**Comment by adaline** [comment]
Check out the docs for each module, for example the core's sample config can be found in `/core/config/example` folder. I will try to simplify the configuration next.

**Comment by prologic** [comment]
Yeah I think a set of sensible defaults would be good with flexible overrides via environment variables in the ``docker-compose.yml``; make sense?

**Comment by adaline** [comment]
My plan is to replace various config files with a single JSON file per module, I think it will make things cleaner and easy to script with external tools :)
Modules already have sensible defaults, the only settings you need to change are those related to your email (domain, mailbox, passwords), examples for which are provided as per the docs.
It is a norm to use environmental vars for settings in docker, I think in this case though it would be awkward to provide config for 5 mailboxes through envs.
The compose file is there as a working example and paths are as per the instructions in docs, i would welcome a PR if you would like to contribute a cleaner solution :)

**Comment by prologic** [comment]
Certainly all other "configurations" should be capable of being "declared" via "environment" i think; with the exception of "users".

For users/passwords I'm thinking of a solution like this:

- link to a "data store"
- on change of the "data store" rewrite out the required file(s)

I *could* probably prototype up something; but is this any advantageous than simply bind mounting a password file into the container?

**Comment by adaline** [comment]
Yeah I think so as well, this is exactly how these images function. User settings are stored in files and containing directory is mounted into a container, which parses the settings in on startup.

**Comment by prologic** [comment]
I'll see if I can spin up dockermail this weekend and maybe a PR against this issue :)

**Comment by adaline** [comment]
Hi James,
Im going to close this issue, if you have more feedback just open up another one :)
Thanks,
Val
