### ISSUE TITLE
Spam filter does not work

### ISSUE THREAD

**Issue by y-ponomarev** [adaline/dockermail#7]
Errors in the file `amavis/boot`.

`/mail_settings/domains`:
```
example.com
example.net

```

1)
```
# readarray -t domains < /mail_settings/domains

# echo "_${domains[@]}_"
_example.com example.net _
```
extra spaces if the file `/mail_settings/domains` has a blank line.

2)
```
# first_fqdn="\$myhostname = \"${domains[0]}\";"

# echo "_${first_fqdn}_"
_$myhostname = "example.com";_
```
Ok.

3) 
```
# domain_string=$(printf "'%s' " "${domains[@]}") | tr ' ' ,

# echo $domain_string
EMPTY!!
```

line mustbe: 
```
# domain_string=$(printf "'%s' " "${domains[@]}" | tr ' ' ,)
# echo $domain_string
'example.com','example.net','',
```

but if emty line in `/mail_settings/domains` additional item `''` appear.

Suggestion:
```
DOMAINS_FILE_NAME="/mail_settings/domains"
first_fqdn="\$myhostname = \"$(grep -v "^\s*$" $DOMAINS_FILE_NAME | head -n 1)\";"
domain_string=$(grep -v "^\s*$" $DOMAINS_FILE_NAME | while read -r line; do echo "'$line'"; done | tr '\n', ',')
domain_acl="@local_domains_acl = ( $domain_string );"
```

**Comment by y-ponomarev** [comment]
There is somebody?

**Comment by adaline** [comment]
Hey @y-ponomarev,
sure im here, working on issues today, will try your addition now

**Comment by adaline** [comment]
I have updated the boot file based on your feedback, let me know if that works for you: 
417364e25b2c5c3afc09bbfa1d832f467a524eb0

**Comment by adaline** [comment]
I will close this issue following the additions above and lack of other activity.
Thank you for the feedback :+1:
