### ISSUE TITLE
Error whilst building core

### ISSUE THREAD

**Issue by ISNIT0** [adaline/dockermail#8]
Hey there, 

Using Core:
Once I have created all of my config files, and then run the build command in the README, I get a bunch of white text, which seems to be installing deps, then it turns red with some errors about the adduser command:
Setting up ssl-cert (1.0.34) ...
Setting up dovecot-core (1:2.2.9-1ubuntu5) ...
chfn: PAM: System error
adduser: `/usr/bin/chfn -f Dovecot mail server dovecot' returned error code 1. Exiting.
chfn: PAM: System error
adduser: `/usr/bin/chfn -f Dovecot login user dovenull' returned error code 1. Exiting.
![screen shot 2015-09-22 at 23 06 33](https://cloud.githubusercontent.com/assets/5173131/10033020/a901f002-617e-11e5-9182-d8fda1b23294.png)

Not sure if related to #6

**Comment by ISNIT0** [comment]
Okay, it's all caused by that pesky apt-get at the beginning, nothing to do with adduser which is not, in fact anything to do with my build failing.

I think it is similar to #6 where dovecot starts before it has stopped (maybe to do with a bug in their package?)

**Comment by ISNIT0** [comment]
Removing line 11:https://github.com/adaline/dockermail/blob/master/core/Dockerfile#L11 from the Dockerfile seems to work, obviously that isn't great though... Fairly certain it is a problem with the Dovecot-imapd installer.

**Comment by adaline** [comment]
Hey Joe,
Yeah there seems to be an issue with dovecot install, i have not had time to play with it much to find the issue.
From a quick look this seems to be the problem: https://github.com/docker/docker/issues/6345

**Comment by adaline** [comment]
Hey @ISNIT0,
the latest master has a workaround for the Docker user bug, can you check that it resolved the issue for you please.

**Comment by ISNIT0** [comment]
Thanks for the help @adaline and sorry for the delay in response.
I'm now getting different errors, about dovecot already being running. I have fiddled with the Dockerfile to get it saying restart instead of start, but I still seem to get an error on build.

Processing triggers for dovecot-core (1:2.2.9-1ubuntu5) ...
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 3130 (read from /var/run/dovecot/master.pid)
   ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dovecot-core
E: Sub-process /usr/bin/dpkg returned an error code (1)
2015/10/18 13:16:25 The command [/bin/sh -c echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d &&    apt-get update && apt-get install -y    ssl-cert    postfix    dovecot-imapd &&    apt-get clean &&    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*] returned a non-zero code: 100

![screen shot 2015-10-18 at 13 16 59](https://cloud.githubusercontent.com/assets/5173131/10564017/9c9f15f8-759a-11e5-8d3c-84d902b160fa.png)

**Comment by adaline** [comment]
Hey @ISNIT0, I think this issue is the same as #6 so i will close this to keep the conversation in one place.
I have updated the code though, so please try again and let us know on #6 how it goes.
Thanks!
